def get_ex_tweets():
    return [
     {'contributors': None,
        'coordinates': None,
        'created_at': 'Thu Sep 09 22:41:38 +0000 2021',
        'display_text_range': [0, 140],
        'entities': {'hashtags': [],
                    'symbols': [],
                    'urls': [],
                    'user_mentions': [{'id': 1349149096909668363,
                                        'id_str': '1349149096909668363',
                                        'indices': [3, 9],
                                        'name': 'President Biden',
                                        'screen_name': 'POTUS'}]},
        'favorite_count': 0,
        'favorited': False,
        'full_text': 'RT @POTUS: Right now, local school officials are trying to '
                    'keep children safe in a pandemic while their governor picks a '
                    'fight with them an…',
        'geo': None,
        'id': 1436097492949610496,
        'id_str': '1436097492949610496',
        'in_reply_to_screen_name': None,
        'in_reply_to_status_id': None,
        'in_reply_to_status_id_str': None,
        'in_reply_to_user_id': None,
        'in_reply_to_user_id_str': None,
        'is_quote_status': False,
        'lang': 'en',
        'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
        'place': None,
        'retweet_count': 2855,
        'retweeted': False,
        'retweeted_status': {'contributors': None,
                            'coordinates': None,
                            'created_at': 'Thu Sep 09 21:35:59 +0000 2021',
                            'display_text_range': [0, 273],
                            'entities': {'hashtags': [],
                                            'symbols': [],
                                            'urls': [],
                                            'user_mentions': []},
                            'favorite_count': 17583,
                            'favorited': False,
                            'full_text': 'Right now, local school officials are '
                                            'trying to keep children safe in a '
                                            'pandemic while their governor picks a '
                                            'fight with them and even threatens their '
                                            'salary and job.\n'
                                            '\n'
                                            'If they will not help us beat the '
                                            'pandemic, I will use my powers as '
                                            'president to get them out of the way.',
                            'geo': None,
                            'id': 1436080973922373639,
                            'id_str': '1436080973922373639',
                            'in_reply_to_screen_name': None,
                            'in_reply_to_status_id': None,
                            'in_reply_to_status_id_str': None,
                            'in_reply_to_user_id': None,
                            'in_reply_to_user_id_str': None,
                            'is_quote_status': False,
                            'lang': 'en',
                            'metadata': {'iso_language_code': 'en',
                                            'result_type': 'recent'},
                            'place': None,
                            'retweet_count': 2855,
                            'retweeted': False,
                            'source': '<a href="https://www.sprinklr.com" '
                                        'rel="nofollow">The White House</a>',
                            'truncated': False,
                            'user': {'contributors_enabled': False,
                                        'created_at': 'Wed Jan 13 00:37:08 +0000 2021',
                                        'default_profile': True,
                                        'default_profile_image': False,
                                        'description': '46th President of the United '
                                                    'States, husband to @FLOTUS, '
                                                    'proud dad & pop. Tweets may be '
                                                    'archived: '
                                                    'https://t.co/IURuMIrzxb',
                                        'entities': {'description': {'urls': [{'display_url': 'whitehouse.gov/privacy',
                                                                            'expanded_url': 'http://whitehouse.gov/privacy',
                                                                            'indices': [98,
                                                                                        121],
                                                                            'url': 'https://t.co/IURuMIrzxb'}]},
                                                    'url': {'urls': [{'display_url': 'WhiteHouse.gov',
                                                                    'expanded_url': 'http://WhiteHouse.gov',
                                                                    'indices': [0,
                                                                                23],
                                                                    'url': 'https://t.co/IxLjEB2zlE'}]}},
                                        'favourites_count': 0,
                                        'follow_request_sent': None,
                                        'followers_count': 13893481,
                                        'following': None,
                                        'friends_count': 12,
                                        'geo_enabled': False,
                                        'has_extended_profile': True,
                                        'id': 1349149096909668363,
                                        'id_str': '1349149096909668363',
                                        'is_translation_enabled': False,
                                        'is_translator': False,
                                        'lang': None,
                                        'listed_count': 13212,
                                        'location': '',
                                        'name': 'President Biden',
                                        'notifications': None,
                                        'profile_background_color': 'F5F8FA',
                                        'profile_background_image_url': None,
                                        'profile_background_image_url_https': None,
                                        'profile_background_tile': False,
                                        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1349149096909668363/1628476962',
                                        'profile_image_url': 'http://pbs.twimg.com/profile_images/1380530524779859970/TfwVAbyX_normal.jpg',
                                        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1380530524779859970/TfwVAbyX_normal.jpg',
                                        'profile_link_color': '1DA1F2',
                                        'profile_sidebar_border_color': 'C0DEED',
                                        'profile_sidebar_fill_color': 'DDEEF6',
                                        'profile_text_color': '333333',
                                        'profile_use_background_image': True,
                                        'protected': False,
                                        'screen_name': 'POTUS',
                                        'statuses_count': 1452,
                                        'time_zone': None,
                                        'translator_type': 'none',
                                        'url': 'https://t.co/IxLjEB2zlE',
                                        'utc_offset': None,
                                        'verified': True,
                                        'withheld_in_countries': []}},
        'source': '<a href="http://twitter.com/download/android" '
                    'rel="nofollow">Twitter for Android</a>',
        'truncated': False,
        'user': {'contributors_enabled': False,
                'created_at': 'Mon Jan 02 02:51:41 +0000 2017',
                'default_profile': False,
                'default_profile_image': False,
                'description': '',
                'entities': {'description': {'urls': []}},
                'favourites_count': 38426,
                'follow_request_sent': None,
                'followers_count': 162,
                'following': None,
                'friends_count': 768,
                'geo_enabled': False,
                'has_extended_profile': True,
                'id': 815752392104935424,
                'id_str': '815752392104935424',
                'is_translation_enabled': False,
                'is_translator': False,
                'lang': None,
                'listed_count': 2,
                'location': '',
                'name': 'Matt Skinner',
                'notifications': None,
                'profile_background_color': '000000',
                'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                'profile_background_tile': False,
                'profile_banner_url': 'https://pbs.twimg.com/profile_banners/815752392104935424/1581307112',
                'profile_image_url': 'http://pbs.twimg.com/profile_images/982352428317270017/NOcEupHx_normal.jpg',
                'profile_image_url_https': 'https://pbs.twimg.com/profile_images/982352428317270017/NOcEupHx_normal.jpg',
                'profile_link_color': 'FF691F',
                'profile_sidebar_border_color': '000000',
                'profile_sidebar_fill_color': '000000',
                'profile_text_color': '000000',
                'profile_use_background_image': False,
                'protected': False,
                'screen_name': 'Skinmatt28',
                'statuses_count': 8576,
                'time_zone': None,
                'translator_type': 'none',
                'url': None,
                'utc_offset': None,
                'verified': False,
                'withheld_in_countries': []}},
        {'contributors': None,
        'coordinates': None,
        'created_at': 'Thu Sep 09 22:41:38 +0000 2021',
        'display_text_range': [0, 140],
        'entities': {'hashtags': [],
                    'symbols': [],
                    'urls': [],
                    'user_mentions': [{'id': 51263592,
                                        'id_str': '51263592',
                                        'indices': [3, 16],
                                        'name': 'Adam Schefter',
                                        'screen_name': 'AdamSchefter'}]},
        'favorite_count': 0,
        'favorited': False,
        'full_text': 'RT @AdamSchefter: Steelers’ OLB T.J. Watt overruled his agents '
                    'who believed they could get more money today, marched into the '
                    'office of Ste…',
        'geo': None,
        'id': 1436097492668477469,
        'id_str': '1436097492668477469',
        'in_reply_to_screen_name': None,
        'in_reply_to_status_id': None,
        'in_reply_to_status_id_str': None,
        'in_reply_to_user_id': None,
        'in_reply_to_user_id_str': None,
        'is_quote_status': False,
        'lang': 'en',
        'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
        'place': None,
        'retweet_count': 2266,
        'retweeted': False,
        'retweeted_status': {'contributors': None,
                            'coordinates': None,
                            'created_at': 'Thu Sep 09 22:14:48 +0000 2021',
                            'display_text_range': [0, 279],
                            'entities': {'hashtags': [],
                                            'symbols': [],
                                            'urls': [],
                                            'user_mentions': []},
                            'favorite_count': 15971,
                            'favorited': False,
                            'full_text': 'Steelers’ OLB T.J. Watt overruled his '
                                            'agents who believed they could get more '
                                            'money today, marched into the office of '
                                            'Steelers president Art Rooney and told '
                                            'him they had a deal. Then the NFL’s new '
                                            'highest-paid defensive player excused '
                                            'himself and announced he had to go work '
                                            'out.',
                            'geo': None,
                            'id': 1436090740187222022,
                            'id_str': '1436090740187222022',
                            'in_reply_to_screen_name': None,
                            'in_reply_to_status_id': None,
                            'in_reply_to_status_id_str': None,
                            'in_reply_to_user_id': None,
                            'in_reply_to_user_id_str': None,
                            'is_quote_status': False,
                            'lang': 'en',
                            'metadata': {'iso_language_code': 'en',
                                            'result_type': 'recent'},
                            'place': None,
                            'retweet_count': 2266,
                            'retweeted': False,
                            'source': '<a href="http://twitter.com/download/iphone" '
                                        'rel="nofollow">Twitter for iPhone</a>',
                            'truncated': False,
                            'user': {'contributors_enabled': False,
                                        'created_at': 'Fri Jun 26 22:55:28 +0000 2009',
                                        'default_profile': False,
                                        'default_profile_image': False,
                                        'description': 'ESPN Senior NFL Insider. \n'
                                                    'Interview & Podcast Requests: '
                                                    'ESPNPR@espn.com\n'
                                                    'Host of the Adam Schefter '
                                                    'Podcast\n'
                                                    'https://t.co/oz43ix5jZU',
                                        'entities': {'description': {'urls': [{'display_url': 'Instagram.com/AdamSchefter',
                                                                            'expanded_url': 'http://Instagram.com/AdamSchefter',
                                                                            'indices': [106,
                                                                                        129],
                                                                            'url': 'https://t.co/oz43ix5jZU'}]},
                                                    'url': {'urls': [{'display_url': 'open.spotify.com/show/42oVKqEPu…',
                                                                    'expanded_url': 'https://open.spotify.com/show/42oVKqEPuf4kFZrXCO7Oh9?si=O1I6pHOYRh2FwJ1R0WbMSQ',
                                                                    'indices': [0,
                                                                                23],
                                                                    'url': 'https://t.co/OUz4GsIjV2'}]}},
                                        'favourites_count': 716,
                                        'follow_request_sent': None,
                                        'followers_count': 8539293,
                                        'following': None,
                                        'friends_count': 3454,
                                        'geo_enabled': True,
                                        'has_extended_profile': True,
                                        'id': 51263592,
                                        'id_str': '51263592',
                                        'is_translation_enabled': True,
                                        'is_translator': False,
                                        'lang': None,
                                        'listed_count': 51169,
                                        'location': 'New York',
                                        'name': 'Adam Schefter',
                                        'notifications': None,
                                        'profile_background_color': '2573B8',
                                        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme4/bg.gif',
                                        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme4/bg.gif',
                                        'profile_background_tile': False,
                                        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/51263592/1466784770',
                                        'profile_image_url': 'http://pbs.twimg.com/profile_images/793924061843914752/ycm8ibEE_normal.jpg',
                                        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/793924061843914752/ycm8ibEE_normal.jpg',
                                        'profile_link_color': '3B94D9',
                                        'profile_sidebar_border_color': 'FFFFFF',
                                        'profile_sidebar_fill_color': '95E8EC',
                                        'profile_text_color': '16101F',
                                        'profile_use_background_image': True,
                                        'protected': False,
                                        'screen_name': 'AdamSchefter',
                                        'statuses_count': 55930,
                                        'time_zone': None,
                                        'translator_type': 'none',
                                        'url': 'https://t.co/OUz4GsIjV2',
                                        'utc_offset': None,
                                        'verified': True,
                                        'withheld_in_countries': []}},
        'source': '<a href="http://twitter.com/download/android" '
                    'rel="nofollow">Twitter for Android</a>',
        'truncated': False,
        'user': {'contributors_enabled': False,
                'created_at': 'Tue Aug 11 16:43:10 +0000 2020',
                'default_profile': True,
                'default_profile_image': False,
                'description': 'Trying to make a dollar outta 15 cents',
                'entities': {'description': {'urls': []}},
                'favourites_count': 1146,
                'follow_request_sent': None,
                'followers_count': 14,
                'following': None,
                'friends_count': 123,
                'geo_enabled': False,
                'has_extended_profile': True,
                'id': 1293226256440283136,
                'id_str': '1293226256440283136',
                'is_translation_enabled': False,
                'is_translator': False,
                'lang': None,
                'listed_count': 0,
                'location': '',
                'name': 'Tony Lewis',
                'notifications': None,
                'profile_background_color': 'F5F8FA',
                'profile_background_image_url': None,
                'profile_background_image_url_https': None,
                'profile_background_tile': False,
                'profile_image_url': 'http://pbs.twimg.com/profile_images/1293226984294641664/Km5UedFr_normal.jpg',
                'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1293226984294641664/Km5UedFr_normal.jpg',
                'profile_link_color': '1DA1F2',
                'profile_sidebar_border_color': 'C0DEED',
                'profile_sidebar_fill_color': 'DDEEF6',
                'profile_text_color': '333333',
                'profile_use_background_image': True,
                'protected': False,
                'screen_name': 'TonyLew92545291',
                'statuses_count': 82,
                'time_zone': None,
                'translator_type': 'none',
                'url': None,
                'utc_offset': None,
                'verified': False,
                'withheld_in_countries': []}},
        {'contributors': None,
        'coordinates': None,
        'created_at': 'Thu Sep 09 22:41:38 +0000 2021',
        'display_text_range': [0, 51],
        'entities': {'hashtags': [], 'symbols': [], 'urls': [], 'user_mentions': []},
        'favorite_count': 0,
        'favorited': False,
        'full_text': 'devo stare svegliw fino alle 6 per l’album di lisa!',
        'geo': None,
        'id': 1436097492622495750,
        'id_str': '1436097492622495750',
        'in_reply_to_screen_name': None,
        'in_reply_to_status_id': None,
        'in_reply_to_status_id_str': None,
        'in_reply_to_user_id': None,
        'in_reply_to_user_id_str': None,
        'is_quote_status': False,
        'lang': 'it',
        'metadata': {'iso_language_code': 'it', 'result_type': 'recent'},
        'place': None,
        'retweet_count': 0,
        'retweeted': False,
        'source': '<a href="http://twitter.com/#!/download/ipad" '
                    'rel="nofollow">Twitter for iPad</a>',
        'truncated': False,
        'user': {'contributors_enabled': False,
                'created_at': 'Sat May 22 14:52:57 +0000 2021',
                'default_profile': True,
                'default_profile_image': False,
                'description': 'they/them - infj',
                'entities': {'description': {'urls': []}},
                'favourites_count': 8090,
                'follow_request_sent': None,
                'followers_count': 566,
                'following': None,
                'friends_count': 618,
                'geo_enabled': False,
                'has_extended_profile': True,
                'id': 1396116829928632327,
                'id_str': '1396116829928632327',
                'is_translation_enabled': False,
                'is_translator': False,
                'lang': None,
                'listed_count': 5,
                'location': '내 작은 별?? oh u mean choi beom gyu!! \n'
                            'yellow (n.) 로제  ✮\n'
                            'italian,minor',
                'name': 'sofia',
                'notifications': None,
                'profile_background_color': 'F5F8FA',
                'profile_background_image_url': None,
                'profile_background_image_url_https': None,
                'profile_background_tile': False,
                'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1396116829928632327/1631223389',
                'profile_image_url': 'http://pbs.twimg.com/profile_images/1436096396889923584/F07InwkM_normal.jpg',
                'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1436096396889923584/F07InwkM_normal.jpg',
                'profile_link_color': '1DA1F2',
                'profile_sidebar_border_color': 'C0DEED',
                'profile_sidebar_fill_color': 'DDEEF6',
                'profile_text_color': '333333',
                'profile_use_background_image': True,
                'protected': False,
                'screen_name': 'TR1GG3RR',
                'statuses_count': 8591,
                'time_zone': None,
                'translator_type': 'none',
                'url': None,
                'utc_offset': None,
                'verified': False,
                'withheld_in_countries': []}},
        {'contributors': None,
        'coordinates': None,
        'created_at': 'Thu Sep 09 22:41:38 +0000 2021',
        'display_text_range': [21, 197],
        'entities': {'hashtags': [],
                    'symbols': [],
                    'urls': [],
                    'user_mentions': [{'id': 21946146,
                                        'id_str': '21946146',
                                        'indices': [0, 8],
                                        'name': 'IKEA black site',
                                        'screen_name': 'Jayseki'},
                                        {'id': 865004396681207809,
                                        'id_str': '865004396681207809',
                                        'indices': [9, 20],
                                        'name': 'Neoliberal 🌐',
                                        'screen_name': 'ne0liberal'}]},
        'favorite_count': 0,
        'favorited': False,
        'full_text': '@Jayseki @ne0liberal a serious third party would absolutely '
                    'focus on local and state elections as opposed to the '
                    'presidency. running for president on a third party ticket is '
                    'not a serious endeavor.',
        'geo': None,
        'id': 1436097492433702912,
        'id_str': '1436097492433702912',
        'in_reply_to_screen_name': 'Jayseki',
        'in_reply_to_status_id': 1436097255505752091,
        'in_reply_to_status_id_str': '1436097255505752091',
        'in_reply_to_user_id': 21946146,
        'in_reply_to_user_id_str': '21946146',
        'is_quote_status': False,
        'lang': 'en',
        'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
        'place': None,
        'retweet_count': 0,
        'retweeted': False,
        'source': '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web '
                    'App</a>',
        'truncated': False,
        'user': {'contributors_enabled': False,
                'created_at': 'Tue Jan 21 13:01:53 +0000 2014',
                'default_profile': False,
                'default_profile_image': False,
                'description': 'Teaching teens about history and government. '
                                'Degrees in polisci, german, and education.🦖fanboy. '
                                'Son. Brother. Husband. BOSTON. I speak only for '
                                'myself 🏳️\u200d🌈',
                'entities': {'description': {'urls': []}},
                'favourites_count': 5202,
                'follow_request_sent': None,
                'followers_count': 117,
                'following': None,
                'friends_count': 1243,
                'geo_enabled': True,
                'has_extended_profile': True,
                'id': 2295431685,
                'id_str': '2295431685',
                'is_translation_enabled': False,
                'is_translator': False,
                'lang': None,
                'listed_count': 1,
                'location': 'Somerville, MA',
                'name': 'Sam Bosbach',
                'notifications': None,
                'profile_background_color': '000000',
                'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                'profile_background_tile': False,
                'profile_banner_url': 'https://pbs.twimg.com/profile_banners/2295431685/1541862796',
                'profile_image_url': 'http://pbs.twimg.com/profile_images/1365872712984522756/hl8EDSYo_normal.jpg',
                'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1365872712984522756/hl8EDSYo_normal.jpg',
                'profile_link_color': '91D2FA',
                'profile_sidebar_border_color': '000000',
                'profile_sidebar_fill_color': '000000',
                'profile_text_color': '000000',
                'profile_use_background_image': False,
                'protected': False,
                'screen_name': 'MRB0SBACH',
                'statuses_count': 2823,
                'time_zone': None,
                'translator_type': 'none',
                'url': None,
                'utc_offset': None,
                'verified': False,
                'withheld_in_countries': []}}
           ]